//
//  MeshBuilder.swift
//  Ashvale
//
//  CPU-side mesh construction. All procedural geometry in the game (terrain,
//  buildings, furniture, vehicles, characters, weapons, items, vegetation)
//  is built with this builder and later uploaded to Metal buffers.
//

import Foundation

/// GPU vertex layout (44 bytes). Must match `VertexIn` in Shaders.metal.
struct Vertex {
    var px: Float, py: Float, pz: Float
    var nx: Float, ny: Float, nz: Float
    var u: Float, v: Float
    /// RGBA8: rgb tint, a = sky visibility / ambient occlusion.
    var color: UInt32
    /// x = texture layer (255 = terrain splat), y = flags, z/w reserved.
    var material: UInt32
    /// Terrain splat weights (grass, dirt, rock, forest floor).
    var weights: UInt32
}

@inline(__always) func packRGBA(_ r: UInt8, _ g: UInt8, _ b: UInt8, _ a: UInt8) -> UInt32 {
    return UInt32(r) | (UInt32(g) << 8) | (UInt32(b) << 16) | (UInt32(a) << 24)
}

@inline(__always) func packColor(_ c: Vec3, _ a: Float) -> UInt32 {
    let r = UInt8(clampf(c.x, 0, 1) * 255 + 0.5)
    let g = UInt8(clampf(c.y, 0, 1) * 255 + 0.5)
    let b = UInt8(clampf(c.z, 0, 1) * 255 + 0.5)
    let aa = UInt8(clampf(a, 0, 1) * 255 + 0.5)
    return packRGBA(r, g, b, aa)
}

/// Texture array layers generated by `TextureFactory`.
enum Mat: UInt8, CaseIterable {
    case grass = 0, dirt, rock, forestFloor
    case asphalt, concrete, brick, plaster, woodPlanks, woodDark, roofTiles, metalPainted
    case metalCorrugated, fabric, floorTiles, linoleum, gravel, bark, foliage, glass
    case rust, canvas, field, wallpaper, burlap, camo, skin, denim, leather, plastic
    case gunMetal, rubber, paper, hair, sheetMetal, carpet
    static let terrain: UInt8 = 255
}

/// Face mask bits for boxes.
struct Faces: OptionSet {
    let rawValue: UInt8
    static let posX = Faces(rawValue: 1 << 0)
    static let negX = Faces(rawValue: 1 << 1)
    static let posY = Faces(rawValue: 1 << 2)
    static let negY = Faces(rawValue: 1 << 3)
    static let posZ = Faces(rawValue: 1 << 4)
    static let negZ = Faces(rawValue: 1 << 5)
    static let all: Faces = [.posX, .negX, .posY, .negY, .posZ, .negZ]
    static let noBottom: Faces = [.posX, .negX, .posY, .posZ, .negZ]
    static let sides: Faces = [.posX, .negX, .posZ, .negZ]
}

final class MeshBuilder {
    var vertices: [Vertex] = []
    var indices: [UInt32] = []
    var bounds = AABB.empty

    // Current state applied to new vertices.
    var color: Vec3 = Vec3(1, 1, 1)
    var skyVisibility: Float = 1
    var material: Mat = .concrete
    var flags: UInt8 = 0
    /// Texture repeats per meter for planar/box mapping.
    var uvScale: Float = 0.5
    /// Optional transform applied to emitted geometry.
    var transform: Mat4 = .identity
    private var transformIsIdentity = true

    init() {}

    var vertexCount: Int { vertices.count }
    var indexCount: Int { indices.count }
    var isEmpty: Bool { indices.isEmpty }

    func reserve(vertices v: Int, indices i: Int) {
        vertices.reserveCapacity(v)
        indices.reserveCapacity(i)
    }

    func setTransform(_ m: Mat4) {
        transform = m
        transformIsIdentity = (m == .identity)
    }

    func withTransform(_ m: Mat4, _ body: () -> Void) {
        let saved = transform
        setTransform(saved * m)
        body()
        setTransform(saved)
    }

    // MARK: Raw emission

    @discardableResult
    @inline(__always)
    func addVertex(_ p: Vec3, _ n: Vec3, _ uv: Vec2, weights: UInt32 = 0, materialOverride: UInt8? = nil, colorOverride: UInt32? = nil) -> UInt32 {
        var wp = p, wn = n
        if !transformIsIdentity {
            wp = transform.transformPoint(p)
            wn = vnormalize(transform.transformDirection(n))
        }
        bounds.expand(wp)
        let mat = UInt32(materialOverride ?? material.rawValue) | (UInt32(flags) << 8)
        let v = Vertex(px: wp.x, py: wp.y, pz: wp.z, nx: wn.x, ny: wn.y, nz: wn.z, u: uv.x, v: uv.y,
                       color: colorOverride ?? packColor(color, skyVisibility), material: mat, weights: weights)
        vertices.append(v)
        return UInt32(vertices.count - 1)
    }

    @inline(__always) func addTriangle(_ a: UInt32, _ b: UInt32, _ c: UInt32) {
        indices.append(a); indices.append(b); indices.append(c)
    }

    /// Adds a quad given counter-clockwise (front-facing) corners.
    func addQuad(_ p0: Vec3, _ p1: Vec3, _ p2: Vec3, _ p3: Vec3, normal n: Vec3,
                 uv0: Vec2, uv1: Vec2, uv2: Vec2, uv3: Vec2) {
        let a = addVertex(p0, n, uv0)
        let b = addVertex(p1, n, uv1)
        let c = addVertex(p2, n, uv2)
        let d = addVertex(p3, n, uv3)
        addTriangle(a, b, c)
        addTriangle(a, c, d)
    }

    /// Quad with automatic flat normal and planar UVs.
    func addQuadAuto(_ p0: Vec3, _ p1: Vec3, _ p2: Vec3, _ p3: Vec3) {
        let n = vnormalize(vcross(p1 - p0, p2 - p0))
        addQuad(p0, p1, p2, p3, normal: n, uv0: planarUV(p0, n), uv1: planarUV(p1, n), uv2: planarUV(p2, n), uv3: planarUV(p3, n))
    }

    func addTriangleAuto(_ p0: Vec3, _ p1: Vec3, _ p2: Vec3) {
        let n = vnormalize(vcross(p1 - p0, p2 - p0))
        let a = addVertex(p0, n, planarUV(p0, n))
        let b = addVertex(p1, n, planarUV(p1, n))
        let c = addVertex(p2, n, planarUV(p2, n))
        addTriangle(a, b, c)
    }

    @inline(__always) func planarUV(_ p: Vec3, _ n: Vec3) -> Vec2 {
        let ax = abs(n.x), ay = abs(n.y), az = abs(n.z)
        if ay >= ax && ay >= az { return Vec2(p.x, p.z) * uvScale }
        if ax >= az { return Vec2(p.z, -p.y) * uvScale }
        return Vec2(p.x, -p.y) * uvScale
    }

    // MARK: Boxes

    /// Axis-aligned box in local space with world-consistent planar UVs.
    func addBox(min a: Vec3, max b: Vec3, faces: Faces = .all) {
        let s = uvScale
        if faces.contains(.posX) {
            addQuad(Vec3(b.x, a.y, b.z), Vec3(b.x, a.y, a.z), Vec3(b.x, b.y, a.z), Vec3(b.x, b.y, b.z), normal: Vec3(1, 0, 0),
                    uv0: Vec2(-b.z, -a.y) * s, uv1: Vec2(-a.z, -a.y) * s, uv2: Vec2(-a.z, -b.y) * s, uv3: Vec2(-b.z, -b.y) * s)
        }
        if faces.contains(.negX) {
            addQuad(Vec3(a.x, a.y, a.z), Vec3(a.x, a.y, b.z), Vec3(a.x, b.y, b.z), Vec3(a.x, b.y, a.z), normal: Vec3(-1, 0, 0),
                    uv0: Vec2(a.z, -a.y) * s, uv1: Vec2(b.z, -a.y) * s, uv2: Vec2(b.z, -b.y) * s, uv3: Vec2(a.z, -b.y) * s)
        }
        if faces.contains(.posY) {
            addQuad(Vec3(a.x, b.y, b.z), Vec3(b.x, b.y, b.z), Vec3(b.x, b.y, a.z), Vec3(a.x, b.y, a.z), normal: Vec3(0, 1, 0),
                    uv0: Vec2(a.x, b.z) * s, uv1: Vec2(b.x, b.z) * s, uv2: Vec2(b.x, a.z) * s, uv3: Vec2(a.x, a.z) * s)
        }
        if faces.contains(.negY) {
            addQuad(Vec3(a.x, a.y, a.z), Vec3(b.x, a.y, a.z), Vec3(b.x, a.y, b.z), Vec3(a.x, a.y, b.z), normal: Vec3(0, -1, 0),
                    uv0: Vec2(a.x, a.z) * s, uv1: Vec2(b.x, a.z) * s, uv2: Vec2(b.x, b.z) * s, uv3: Vec2(a.x, b.z) * s)
        }
        if faces.contains(.posZ) {
            addQuad(Vec3(a.x, a.y, b.z), Vec3(b.x, a.y, b.z), Vec3(b.x, b.y, b.z), Vec3(a.x, b.y, b.z), normal: Vec3(0, 0, 1),
                    uv0: Vec2(a.x, -a.y) * s, uv1: Vec2(b.x, -a.y) * s, uv2: Vec2(b.x, -b.y) * s, uv3: Vec2(a.x, -b.y) * s)
        }
        if faces.contains(.negZ) {
            addQuad(Vec3(b.x, a.y, a.z), Vec3(a.x, a.y, a.z), Vec3(a.x, b.y, a.z), Vec3(b.x, b.y, a.z), normal: Vec3(0, 0, -1),
                    uv0: Vec2(-b.x, -a.y) * s, uv1: Vec2(-a.x, -a.y) * s, uv2: Vec2(-a.x, -b.y) * s, uv3: Vec2(-b.x, -b.y) * s)
        }
    }

    func addBox(center c: Vec3, size: Vec3, faces: Faces = .all) {
        addBox(min: c - size * 0.5, max: c + size * 0.5, faces: faces)
    }

    /// Box with chamfered (beveled) vertical edges for softer silhouettes.
    func addBeveledBox(min a: Vec3, max b: Vec3, bevel r: Float) {
        let bx = Swift.min(r, (b.x - a.x) * 0.45), bz = Swift.min(r, (b.z - a.z) * 0.45)
        let pts: [Vec2] = [Vec2(a.x + bx, a.z), Vec2(b.x - bx, a.z), Vec2(b.x, a.z + bz), Vec2(b.x, b.z - bz),
                           Vec2(b.x - bx, b.z), Vec2(a.x + bx, b.z), Vec2(a.x, b.z - bz), Vec2(a.x, a.z + bz)]
        addPrismY(pts, y0: a.y, y1: b.y)
    }

    /// Extrudes a convex or simple polygon in the XZ plane (counter-clockwise when viewed from +Y)
    /// between heights y0 and y1.
    func addPrismY(_ poly: [Vec2], y0: Float, y1: Float, caps: Bool = true) {
        let n = poly.count
        guard n >= 3 else { return }
        let ccw = signedArea(poly) > 0
        var run: Float = 0
        for i in 0..<n {
            let p = poly[i], q = poly[(i + 1) % n]
            let edge = q - p
            let len = vlength2(edge)
            if len < 1e-6 { continue }
            // Polygon coordinates are (x, z). For a CCW polygon in that plane the outward
            // normal of an edge is to its right: (edge.z, -edge.x).
            let r = ccw ? Vec2(edge.y, -edge.x) : Vec2(-edge.y, edge.x)
            let nrm = vnormalize(Vec3(r.x, 0, r.y))
            let p0 = Vec3(p.x, y0, p.y), p1 = Vec3(q.x, y0, q.y), p2 = Vec3(q.x, y1, q.y), p3 = Vec3(p.x, y1, p.y)
            let u0 = run * uvScale, u1 = (run + len) * uvScale
            let faceN = vcross(p1 - p0, p2 - p0)
            if vdot(faceN, nrm) >= 0 {
                addQuad(p0, p1, p2, p3, normal: nrm, uv0: Vec2(u0, -y0 * uvScale), uv1: Vec2(u1, -y0 * uvScale),
                        uv2: Vec2(u1, -y1 * uvScale), uv3: Vec2(u0, -y1 * uvScale))
            } else {
                addQuad(p1, p0, p3, p2, normal: nrm, uv0: Vec2(u1, -y0 * uvScale), uv1: Vec2(u0, -y0 * uvScale),
                        uv2: Vec2(u0, -y1 * uvScale), uv3: Vec2(u1, -y1 * uvScale))
            }
            run += len
        }
        if caps {
            let tris = triangulate(poly)
            for t in tris {
                let a = poly[t.0], b = poly[t.1], c = poly[t.2]
                addOrientedTriangle(Vec3(a.x, y1, a.y), Vec3(b.x, y1, b.y), Vec3(c.x, y1, c.y), want: Vec3(0, 1, 0))
                addOrientedTriangle(Vec3(a.x, y0, a.y), Vec3(b.x, y0, b.y), Vec3(c.x, y0, c.y), want: Vec3(0, -1, 0))
            }
        }
    }

    /// Extrudes a polygon defined in the XY plane along Z from z0 to z1 (profile shapes: vehicles, gun stocks).
    func addPrismZ(_ poly: [Vec2], z0: Float, z1: Float, caps: Bool = true) {
        let n = poly.count
        guard n >= 3 else { return }
        let ccw = signedArea(poly) > 0
        var run: Float = 0
        for i in 0..<n {
            let p = poly[i], q = poly[(i + 1) % n]
            let edge = q - p
            let len = vlength2(edge)
            if len < 1e-6 { continue }
            // For a CCW polygon in the XY plane the outward normal is to the right of each edge.
            let r = ccw ? Vec2(edge.y, -edge.x) : Vec2(-edge.y, edge.x)
            let nrm = vnormalize(Vec3(r.x, r.y, 0))
            let p0 = Vec3(p.x, p.y, z0), p1 = Vec3(q.x, q.y, z0), p2 = Vec3(q.x, q.y, z1), p3 = Vec3(p.x, p.y, z1)
            let u0 = run * uvScale, u1 = (run + len) * uvScale
            let faceN = vcross(p1 - p0, p2 - p0)
            if vdot(faceN, nrm) >= 0 {
                addQuad(p0, p1, p2, p3, normal: nrm, uv0: Vec2(u0, z0 * uvScale), uv1: Vec2(u1, z0 * uvScale),
                        uv2: Vec2(u1, z1 * uvScale), uv3: Vec2(u0, z1 * uvScale))
            } else {
                addQuad(p1, p0, p3, p2, normal: nrm, uv0: Vec2(u1, z0 * uvScale), uv1: Vec2(u0, z0 * uvScale),
                        uv2: Vec2(u0, z1 * uvScale), uv3: Vec2(u1, z1 * uvScale))
            }
            run += len
        }
        if caps {
            for t in triangulate(poly) {
                let a = poly[t.0], b = poly[t.1], cc = poly[t.2]
                addOrientedTriangle(Vec3(a.x, a.y, z1), Vec3(b.x, b.y, z1), Vec3(cc.x, cc.y, z1), want: Vec3(0, 0, 1))
                addOrientedTriangle(Vec3(a.x, a.y, z0), Vec3(b.x, b.y, z0), Vec3(cc.x, cc.y, z0), want: Vec3(0, 0, -1))
            }
        }
    }

    /// Adds a triangle wound so that its face normal matches `want`.
    func addOrientedTriangle(_ a: Vec3, _ b: Vec3, _ c: Vec3, want: Vec3) {
        let n = vcross(b - a, c - a)
        let nn = vnormalize(want)
        if vdot(n, want) >= 0 {
            let i0 = addVertex(a, nn, planarUV(a, nn)), i1 = addVertex(b, nn, planarUV(b, nn)), i2 = addVertex(c, nn, planarUV(c, nn))
            addTriangle(i0, i1, i2)
        } else {
            let i0 = addVertex(a, nn, planarUV(a, nn)), i1 = addVertex(c, nn, planarUV(c, nn)), i2 = addVertex(b, nn, planarUV(b, nn))
            addTriangle(i0, i1, i2)
        }
    }

    // MARK: Round shapes

    /// Cylinder / truncated cone along +Y from y0 to y1, centered at (cx, cz).
    func addCylinder(center c: Vec3, radiusBottom r0: Float, radiusTop r1: Float, height h: Float,
                     segments: Int = 10, capTop: Bool = true, capBottom: Bool = true) {
        let base = UInt32(vertices.count)
        let circ = kTwoPi * Swift.max(r0, r1)
        let slope = (r0 - r1) / Swift.max(h, 1e-4)
        for i in 0...segments {
            let a = Float(i) / Float(segments) * kTwoPi
            let ca = cosf(a), sa = sinf(a)
            let n = vnormalize(Vec3(ca, slope, sa))
            let u = Float(i) / Float(segments) * circ * uvScale
            addVertex(Vec3(c.x + ca * r0, c.y, c.z + sa * r0), n, Vec2(u, 0))
            addVertex(Vec3(c.x + ca * r1, c.y + h, c.z + sa * r1), n, Vec2(u, -h * uvScale))
        }
        for i in 0..<segments {
            let i0 = base + UInt32(i * 2), i1 = i0 + 1, i2 = i0 + 2, i3 = i0 + 3
            addTriangle(i0, i1, i2)
            addTriangle(i2, i1, i3)
        }
        if capTop && r1 > 1e-4 { addDisc(center: Vec3(c.x, c.y + h, c.z), radius: r1, up: true, segments: segments) }
        if capBottom && r0 > 1e-4 { addDisc(center: c, radius: r0, up: false, segments: segments) }
    }

    func addDisc(center c: Vec3, radius r: Float, up: Bool, segments: Int) {
        let n = Vec3(0, up ? 1 : -1, 0)
        let center = addVertex(c, n, Vec2(c.x, c.z) * uvScale)
        var ring: [UInt32] = []
        for i in 0...segments {
            let a = Float(i) / Float(segments) * kTwoPi
            let p = Vec3(c.x + cosf(a) * r, c.y, c.z + sinf(a) * r)
            ring.append(addVertex(p, n, Vec2(p.x, p.z) * uvScale))
        }
        for i in 0..<segments {
            if up { addTriangle(center, ring[i + 1], ring[i]) } else { addTriangle(center, ring[i], ring[i + 1]) }
        }
    }

    /// Ellipsoid centered at c with radii r.
    func addEllipsoid(center c: Vec3, radii r: Vec3, rings: Int = 8, segments: Int = 12, jitter: Float = 0, seed: UInt32 = 0) {
        let base = UInt32(vertices.count)
        for j in 0...rings {
            let v = Float(j) / Float(rings)
            let phi = v * kPi
            for i in 0...segments {
                let u = Float(i) / Float(segments)
                let th = u * kTwoPi
                var dir = Vec3(sinf(phi) * cosf(th), cosf(phi), sinf(phi) * sinf(th))
                if jitter > 0 && j > 0 && j < rings {
                    let ii = i == segments ? 0 : i
                    let h = hashFloat(Int32(ii), Int32(j), seed)
                    dir *= (1 + (h - 0.5) * jitter)
                }
                let p = c + dir * r
                let n = vnormalize(Vec3(dir.x / r.x, dir.y / r.y, dir.z / r.z))
                addVertex(p, n, Vec2(u * kTwoPi * Swift.max(r.x, r.z), v * kPi * r.y) * uvScale)
            }
        }
        let stride = UInt32(segments + 1)
        for j in 0..<rings {
            for i in 0..<segments {
                let a = base + UInt32(j) * stride + UInt32(i)
                let b = a + stride
                addTriangle(a, a + 1, b)
                addTriangle(a + 1, b + 1, b)
            }
        }
    }

    /// Tapered capsule from point a (radius ra) to point b (radius rb).
    func addCapsule(from a: Vec3, to b: Vec3, radiusA ra: Float, radiusB rb: Float, segments: Int = 8, rings: Int = 3) {
        let axis = b - a
        let len = vlength(axis)
        guard len > 1e-5 else {
            addEllipsoid(center: a, radii: Vec3(repeating: ra), rings: 6, segments: segments)
            return
        }
        let up = axis / len
        var side = vcross(up, Vec3(0, 0, 1))
        if vlengthSq(side) < 1e-4 { side = vcross(up, Vec3(1, 0, 0)) }
        side = vnormalize(side)
        let fwd = vcross(side, up)
        let m = Mat4.basis(right: side, up: up, back: fwd, origin: a)
        withTransform(m) {
            // Profile rings from the bottom pole (hemisphere around a) to the top pole (hemisphere around b).
            var profile: [(y: Float, r: Float, ny: Float)] = []
            for j in 0...rings {
                let t = Float(j) / Float(rings) * (kPi * 0.5) // 0 = pole
                profile.append((y: -cosf(t) * ra, r: sinf(t) * ra, ny: -cosf(t)))
            }
            for j in 0...rings {
                let t = Float(j) / Float(rings) * (kPi * 0.5) // 0 = equator
                profile.append((y: len + sinf(t) * rb, r: cosf(t) * rb, ny: sinf(t)))
            }
            let base = UInt32(vertices.count)
            let stride = UInt32(segments + 1)
            for (k, pr) in profile.enumerated() {
                for i in 0...segments {
                    let th = Float(i) / Float(segments) * kTwoPi
                    let ct = cosf(th), st = sinf(th)
                    let nxz = sqrtf(Swift.max(0, 1 - pr.ny * pr.ny))
                    let n = Vec3(ct * nxz, pr.ny, st * nxz)
                    addVertex(Vec3(ct * pr.r, pr.y, st * pr.r), n, Vec2(Float(i) / Float(segments) * kTwoPi * ra, pr.y) * uvScale * 4)
                }
                if k > 0 {
                    for i in 0..<segments {
                        let p0 = base + UInt32(k - 1) * stride + UInt32(i)
                        let p1 = base + UInt32(k) * stride + UInt32(i)
                        addTriangle(p0, p1, p0 + 1)
                        addTriangle(p0 + 1, p1, p1 + 1)
                    }
                }
            }
        }
    }

    /// Triangular prism roof between two gable ends (ridge along local Z).
    func addGableRoof(minX: Float, maxX: Float, minZ: Float, maxZ: Float, baseY: Float, ridgeHeight: Float, overhang: Float, thickness: Float) {
        let x0 = minX - overhang, x1 = maxX + overhang
        let z0 = minZ - overhang, z1 = maxZ + overhang
        let midX = (minX + maxX) * 0.5
        let top = baseY + ridgeHeight
        // Slope surfaces.
        addQuadAuto(Vec3(x0, baseY, z1), Vec3(midX, top, z1), Vec3(midX, top, z0), Vec3(x0, baseY, z0))
        addQuadAuto(Vec3(midX, top, z1), Vec3(x1, baseY, z1), Vec3(x1, baseY, z0), Vec3(midX, top, z0))
        // Undersides (visible from attic / eaves).
        let t = thickness
        addQuadAuto(Vec3(x0, baseY - t, z0), Vec3(midX, top - t, z0), Vec3(midX, top - t, z1), Vec3(x0, baseY - t, z1))
        addQuadAuto(Vec3(midX, top - t, z0), Vec3(x1, baseY - t, z0), Vec3(x1, baseY - t, z1), Vec3(midX, top - t, z1))
        // Fascia edges.
        addQuadAuto(Vec3(x0, baseY - t, z1), Vec3(x0, baseY, z1), Vec3(x0, baseY, z0), Vec3(x0, baseY - t, z0))
        addQuadAuto(Vec3(x1, baseY - t, z0), Vec3(x1, baseY, z0), Vec3(x1, baseY, z1), Vec3(x1, baseY - t, z1))
    }

    /// Triangular gable wall infill (in the XY plane at z) between x0..x1 rising to ridge.
    func addGableTriangle(x0: Float, x1: Float, z: Float, baseY: Float, ridgeHeight: Float, facingPositiveZ: Bool) {
        let mid = (x0 + x1) * 0.5
        let a = Vec3(x0, baseY, z), b = Vec3(x1, baseY, z), c = Vec3(mid, baseY + ridgeHeight, z)
        addOrientedTriangle(a, b, c, want: Vec3(0, 0, facingPositiveZ ? 1 : -1))
    }

    // MARK: Composition

    /// Appends another builder's geometry, transformed.
    func append(_ other: MeshBuilder, transform m: Mat4 = .identity) {
        let base = UInt32(vertices.count)
        let identity = (m == .identity)
        vertices.reserveCapacity(vertices.count + other.vertices.count)
        for var v in other.vertices {
            if !identity {
                let p = m.transformPoint(Vec3(v.px, v.py, v.pz))
                let n = vnormalize(m.transformDirection(Vec3(v.nx, v.ny, v.nz)))
                v.px = p.x; v.py = p.y; v.pz = p.z
                v.nx = n.x; v.ny = n.y; v.nz = n.z
            }
            bounds.expand(Vec3(v.px, v.py, v.pz))
            vertices.append(v)
        }
        indices.reserveCapacity(indices.count + other.indices.count)
        for i in other.indices { indices.append(i + base) }
    }

    /// Recenters geometry so the bounds' bottom-center sits at the origin (used for items).
    func recenterBottom() {
        guard bounds.isValid else { return }
        let c = Vec3((bounds.min.x + bounds.max.x) * 0.5, bounds.min.y, (bounds.min.z + bounds.max.z) * 0.5)
        for i in 0..<vertices.count {
            vertices[i].px -= c.x; vertices[i].py -= c.y; vertices[i].pz -= c.z
        }
        bounds = AABB(min: bounds.min - c, max: bounds.max - c)
    }

    var triangleCount: Int { indices.count / 3 }
}

// MARK: - Polygon triangulation (ear clipping)

func signedArea(_ poly: [Vec2]) -> Float {
    var a: Float = 0
    for i in 0..<poly.count {
        let p = poly[i], q = poly[(i + 1) % poly.count]
        a += p.x * q.y - q.x * p.y
    }
    return a * 0.5
}

func triangulate(_ poly: [Vec2]) -> [(Int, Int, Int)] {
    let n = poly.count
    if n < 3 { return [] }
    var area: Float = 0
    for i in 0..<n {
        let p = poly[i], q = poly[(i + 1) % n]
        area += p.x * q.y - q.x * p.y
    }
    var idx = Array(0..<n)
    if area < 0 { idx.reverse() }
    var result: [(Int, Int, Int)] = []
    var guardCount = 0
    while idx.count > 3 && guardCount < 1000 {
        guardCount += 1
        var earFound = false
        for i in 0..<idx.count {
            let i0 = idx[(i + idx.count - 1) % idx.count], i1 = idx[i], i2 = idx[(i + 1) % idx.count]
            let a = poly[i0], b = poly[i1], c = poly[i2]
            let cross = (b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x)
            if cross <= 1e-9 { continue }
            var contains = false
            for j in idx where j != i0 && j != i1 && j != i2 {
                if pointInTriangle(poly[j], a, b, c) { contains = true; break }
            }
            if contains { continue }
            result.append((i0, i1, i2))
            idx.remove(at: i)
            earFound = true
            break
        }
        if !earFound { break }
    }
    if idx.count == 3 { result.append((idx[0], idx[1], idx[2])) }
    return result
}

private func pointInTriangle(_ p: Vec2, _ a: Vec2, _ b: Vec2, _ c: Vec2) -> Bool {
    let d1 = (p.x - b.x) * (a.y - b.y) - (a.x - b.x) * (p.y - b.y)
    let d2 = (p.x - c.x) * (b.y - c.y) - (b.x - c.x) * (p.y - c.y)
    let d3 = (p.x - a.x) * (c.y - a.y) - (c.x - a.x) * (p.y - a.y)
    let hasNeg = (d1 < 0) || (d2 < 0) || (d3 < 0)
    let hasPos = (d1 > 0) || (d2 > 0) || (d3 > 0)
    return !(hasNeg && hasPos)
}
